"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from authlete.errors import AuthleteError
from authlete.types import BaseModel
import httpx
from typing import Optional


class APIErrorNotFoundData(BaseModel):
    status: int

    error: str

    code: str


class APIErrorNotFound(AuthleteError):
    r"""Not Found error"""

    data: APIErrorNotFoundData

    def __init__(
        self,
        data: APIErrorNotFoundData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        self.data = data
