"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from authlete.errors import AuthleteError
from authlete.types import BaseModel
import httpx
from typing import Optional


class APIErrorUnauthorizedData(BaseModel):
    status: int

    error: str


class APIErrorUnauthorized(AuthleteError):
    r"""Unauthorized error"""

    data: APIErrorUnauthorizedData

    def __init__(
        self,
        data: APIErrorUnauthorizedData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        self.data = data
