# name: SDK Generation via Dispatch

# on:
#   repository_dispatch:
#     types: [trigger-authlete-sdk-generation]

# permissions:
#   checks: write
#   contents: write
#   pull-requests: write
#   statuses: write
#   id-token: write

# jobs:
#   generate:
#     uses: speakeasy-api/sdk-generation-action/.github/workflows/workflow-executor.yaml@v15
#     with:
#       force: true
#       mode: pr
#       set_version: ''
#     secrets:
#       github_access_token: ${{ secrets.GITHUB_TOKEN }}
#       pypi_token: ${{ secrets.PYPI_TOKEN }}
#       speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}
name: Generate
permissions:
  checks: write
  contents: write
  pull-requests: write
  statuses: write
  id-token: write
"on":
  workflow_dispatch:
    inputs:
      force:
        description: Force generation of SDKs
        type: boolean
        default: false
      set_version:
        description: optionally set a specific SDK version
        type: string
  schedule:
    - cron: 0 0 * * *
jobs:
  generate:
    uses: speakeasy-api/sdk-generation-action/.github/workflows/workflow-executor.yaml@v15
    with:
      force: ${{ github.event.inputs.force }}
      mode: pr
      set_version: ${{ github.event.inputs.set_version }}
    secrets:
      github_access_token: ${{ secrets.GITHUB_TOKEN }}
      pypi_token: ${{ secrets.PYPI_TOKEN }}
      speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}
